"""create users table

Revision ID: 6377a309937a
Revises: 6724ca471deb
Create Date: 2026-07-14 06:47:49.209325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '6377a309937a'
down_revision: Union[str, Sequence[str], None] = '6724ca471deb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
